[[redirects]]
  from = "/.well-known/*"
  to = "/.netlify/functions/mcp"
  status = 200
  force = true

[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/mcp"
  status = 200
  force = true

[[redirects]]
  from = "/message"
  to = "/.netlify/functions/mcp"
  status = 200
  force = true
